openapi: 3.0.3
info:
  title: Synctera API
  version: {{trimPrefix .Version "v"}}.UPDATE_ME.0
  description: |
    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.synctera.com/{{.Version}}
    description: Production
  - url: https://api-sandbox.synctera.com/{{.Version}}
    description: Sandbox (no real world financial impact)
# top level keys are interpreted as json paths
components.securitySchemes:
  bearerAuth:
    bearerFormat: api_key
    scheme: bearer
    type: http
