#!/usr/bin/env bash

set -e

start_dir=$(pwd)
spec_dir=$(mktemp --directory --suffix .spec)

cp --recursive common/ "${spec_dir}"

cd cmd/gather_openapi_specs
go run . --output "${spec_dir}" \
	--project "mainapi:${MAINAPI_OPENAPI_BRANCH}" \
	--external accounts \
	--external customers \
	--external disclosures \
	--external kyc \
	--external rdc \
	--external reconciliations \
	--external transactions \
	--project "webhook:${WEBHOOK_OPENAPI_BRANCH}" \
	--external webhooks \
	--project "cards:${CARDS_OPENAPI_BRANCH}" \
	--external cards \
	--project "trisk:${TRISK_OPENAPI_BRANCH}" \
	--external transactions

cd "${spec_dir}"

openapi-merge-cli --config merge-internal-apis.json
openapi-merge-cli --config merge-external-apis.json

# override each spec with header.yml to ensure they all match openapi version, our version and our servers
for spec in *-api-bundled.yml; do
  for field in openapi info servers; do
    yq eval-all "select(fileIndex==0).${field} = select(fileIndex==1).${field} | select(fileIndex==0)" "${spec}" "${start_dir}/header.yml" > ".tmp.${spec}"
    mv ".tmp.${spec}" "${spec}"
  done
done

for spec in **/api.yml *-api-merged-bundled.yml; do
  swagger-cli validate "$spec"
  openapi lint "$spec"
done

cp ./*-api-merged-bundled.yml "${start_dir}"
