#!/usr/bin/env bash

set -e

start_dir=$(pwd)
spec_dir=$(mktemp --directory --suffix .spec)

cd cmd/pull_specs
go run . --output "${spec_dir}" \
	--project "mainapi:${MAINAPI_OPENAPI_BRANCH}" \
	--internal users \
	--internal signups \
#	--project "webhook:${WEBHOOK_OPENAPI_BRANCH}" \

cd "${spec_dir}"

openapi-merge-cli --config merge-internal-apis.json
openapi-merge-cli --config merge-external-apis.json

cp ./*-api-merged-bundled.yml "${start_dir}"
