components:
  parameters:

    execution_date:
      name: ACH execution date
      description: Execution Date
      in: query
      required: true
      schema:
        type: string
        format: date
        example: faker.date.past

    payment_id:
      name: payment_id 
      description: Payment ID
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: faker.random.uuid
        