/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customers

import (
	"encoding/json"
	"fmt"
)

// Account - Account
type Account struct {
	LeadModeAccount *LeadModeAccount
	ShadowModeAccount *ShadowModeAccount
}

// LeadModeAccountAsAccount is a convenience function that returns LeadModeAccount wrapped in Account
func LeadModeAccountAsAccount(v *LeadModeAccount) Account {
	return Account{ LeadModeAccount: v}
}

// ShadowModeAccountAsAccount is a convenience function that returns ShadowModeAccount wrapped in Account
func ShadowModeAccountAsAccount(v *ShadowModeAccount) Account {
	return Account{ ShadowModeAccount: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Account) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LeadModeAccount
	err = json.Unmarshal(data, &dst.LeadModeAccount)
	if err == nil {
		jsonLeadModeAccount, _ := json.Marshal(dst.LeadModeAccount)
		if string(jsonLeadModeAccount) == "{}" { // empty struct
			dst.LeadModeAccount = nil
		} else {
			match++
		}
	} else {
		dst.LeadModeAccount = nil
	}

	// try to unmarshal data into ShadowModeAccount
	err = json.Unmarshal(data, &dst.ShadowModeAccount)
	if err == nil {
		jsonShadowModeAccount, _ := json.Marshal(dst.ShadowModeAccount)
		if string(jsonShadowModeAccount) == "{}" { // empty struct
			dst.ShadowModeAccount = nil
		} else {
			match++
		}
	} else {
		dst.ShadowModeAccount = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LeadModeAccount = nil
		dst.ShadowModeAccount = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(Account)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(Account)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Account) MarshalJSON() ([]byte, error) {
	if src.LeadModeAccount != nil {
		return json.Marshal(&src.LeadModeAccount)
	}

	if src.ShadowModeAccount != nil {
		return json.Marshal(&src.ShadowModeAccount)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Account) GetActualInstance() (interface{}) {
	if obj.LeadModeAccount != nil {
		return obj.LeadModeAccount
	}

	if obj.ShadowModeAccount != nil {
		return obj.ShadowModeAccount
	}

	// all schemas are nil
	return nil
}

type NullableAccount struct {
	value *Account
	isSet bool
}

func (v NullableAccount) Get() *Account {
	return v.value
}

func (v *NullableAccount) Set(val *Account) {
	v.value = val
	v.isSet = true
}

func (v NullableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccount(val *Account) *NullableAccount {
	return &NullableAccount{value: val, isSet: true}
}

func (v NullableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


