/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package customers

import (
	"encoding/json"
)

// Relationship struct for Relationship
type Relationship struct {
	// ID of related entity
	Id *string `json:"id,omitempty"`
	RelationshipRole *RelationshipRole `json:"relationship_role,omitempty"`
}

// NewRelationship instantiates a new Relationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationship() *Relationship {
	this := Relationship{}
	return &this
}

// NewRelationshipWithDefaults instantiates a new Relationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipWithDefaults() *Relationship {
	this := Relationship{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Relationship) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Relationship) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Relationship) SetId(v string) {
	o.Id = &v
}

// GetRelationshipRole returns the RelationshipRole field value if set, zero value otherwise.
func (o *Relationship) GetRelationshipRole() RelationshipRole {
	if o == nil || o.RelationshipRole == nil {
		var ret RelationshipRole
		return ret
	}
	return *o.RelationshipRole
}

// GetRelationshipRoleOk returns a tuple with the RelationshipRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Relationship) GetRelationshipRoleOk() (*RelationshipRole, bool) {
	if o == nil || o.RelationshipRole == nil {
		return nil, false
	}
	return o.RelationshipRole, true
}

// HasRelationshipRole returns a boolean if a field has been set.
func (o *Relationship) HasRelationshipRole() bool {
	if o != nil && o.RelationshipRole != nil {
		return true
	}

	return false
}

// SetRelationshipRole gets a reference to the given RelationshipRole and assigns it to the RelationshipRole field.
func (o *Relationship) SetRelationshipRole(v RelationshipRole) {
	o.RelationshipRole = &v
}

func (o Relationship) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.RelationshipRole != nil {
		toSerialize["relationship_role"] = o.RelationshipRole
	}
	return json.Marshal(toSerialize)
}

type NullableRelationship struct {
	value *Relationship
	isSet bool
}

func (v NullableRelationship) Get() *Relationship {
	return v.value
}

func (v *NullableRelationship) Set(val *Relationship) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationship(val *Relationship) *NullableRelationship {
	return &NullableRelationship{value: val, isSet: true}
}

func (v NullableRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


