components:
  parameters:

    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 100
        description: Maximum of objects to return per page
        example: 100

    mfa_token:
      name: mfa_token
      description: Multi-Factor Authentication Token
      in: header
      schema:
        type: string
        pattern: '^\d{4,8}$'
        writeOnly: true
        example: faker.helpers.replaceSymbols(######)
        
    page_token:
      name: page_token
      in: query
      required: false
      schema:
        type: string
        description: Optional pagination token to be provided to retrieve subsequent pages, returned from previous get
        example: faker.random.alphaNumeric(10)

    # IDs included here to prevent import cycles
    customer_id:
      name: customer_id
      description: Customer ID
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: faker.random.uuid