components:
  parameters:
    limit:
      name: limit
      in: query
      x-external: true
      required: false
      schema:
        type: integer
        minimum: 1
        default: 100
        description: >
          Maximum number of objects to return per page.
          If the limit is greater than 100, then it will be set to 100.
        example: 100

    page_token:
      name: page_token
      in: query
      x-external: true
      required: false
      schema:
        type: string
        description: Optional pagination token to be provided to retrieve subsequent pages, returned from previous get
        example: a8937a0d

    tenant:
      name: tenant
      in: query
      x-external: false
      required: false
      schema:
        type: string
        description: Only return resources owned by the specified tenant
        example: abcdef_ghijlk
    
    tenant_id_path:
      name: tenant_id
      in: path
      x-external: false
      required: true
      schema:
        type: string
        pattern: ^(\d{1,}|\*)_(\d{1,}|\*)$
        description: Only return resources owned by the specified tenant
        example: "2_3"

    id:
      name: id
      description: Unique resource identifier
      in: query
      x-external: true
      required: false
      schema:
        type: array
        items:
          type: string
          format: uuid
          example: 7d943c51-e4ff-4e57-9558-08cab6b963c7
      style: form
      explode: false

    idempotency_key:
      name: Idempotency-Key
      in: header
      x-external: true
      required: false
      description: >-
        An idempotency key is an arbitrary unique value generated by client to
        detect subsequent retries of the same request. It is recommended that a
        UUID or a similar random identifier be used as an idempotency key.
        A different key must be used for each request, unless it is a retry.
      schema:
        type: string
        example: 7d943c51-e4ff-4e57-9558-08cab6b963c7
