/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signups

import (
	"encoding/json"
)

// SignupIds Signup output names
type SignupIds struct {
	// Bank ID
	BankId int32 `json:"bank_id"`
	// Partner ID
	PartnerId int32 `json:"partner_id"`
	// Bank's party's party_user_id
	PartyUserId int32 `json:"party_user_id"`
	// Party UUIID
	PartyUuid string `json:"party_uuid"`
}

// NewSignupIds instantiates a new SignupIds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupIds(bankId int32, partnerId int32, partyUserId int32, partyUuid string) *SignupIds {
	this := SignupIds{}
	this.BankId = bankId
	this.PartnerId = partnerId
	this.PartyUserId = partyUserId
	this.PartyUuid = partyUuid
	return &this
}

// NewSignupIdsWithDefaults instantiates a new SignupIds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupIdsWithDefaults() *SignupIds {
	this := SignupIds{}
	return &this
}

// GetBankId returns the BankId field value
func (o *SignupIds) GetBankId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *SignupIds) GetBankIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *SignupIds) SetBankId(v int32) {
	o.BankId = v
}

// GetPartnerId returns the PartnerId field value
func (o *SignupIds) GetPartnerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartnerId
}

// GetPartnerIdOk returns a tuple with the PartnerId field value
// and a boolean to check if the value has been set.
func (o *SignupIds) GetPartnerIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PartnerId, true
}

// SetPartnerId sets field value
func (o *SignupIds) SetPartnerId(v int32) {
	o.PartnerId = v
}

// GetPartyUserId returns the PartyUserId field value
func (o *SignupIds) GetPartyUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartyUserId
}

// GetPartyUserIdOk returns a tuple with the PartyUserId field value
// and a boolean to check if the value has been set.
func (o *SignupIds) GetPartyUserIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PartyUserId, true
}

// SetPartyUserId sets field value
func (o *SignupIds) SetPartyUserId(v int32) {
	o.PartyUserId = v
}

// GetPartyUuid returns the PartyUuid field value
func (o *SignupIds) GetPartyUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartyUuid
}

// GetPartyUuidOk returns a tuple with the PartyUuid field value
// and a boolean to check if the value has been set.
func (o *SignupIds) GetPartyUuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PartyUuid, true
}

// SetPartyUuid sets field value
func (o *SignupIds) SetPartyUuid(v string) {
	o.PartyUuid = v
}

func (o SignupIds) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bank_id"] = o.BankId
	}
	if true {
		toSerialize["partner_id"] = o.PartnerId
	}
	if true {
		toSerialize["party_user_id"] = o.PartyUserId
	}
	if true {
		toSerialize["party_uuid"] = o.PartyUuid
	}
	return json.Marshal(toSerialize)
}

type NullableSignupIds struct {
	value *SignupIds
	isSet bool
}

func (v NullableSignupIds) Get() *SignupIds {
	return v.value
}

func (v *NullableSignupIds) Set(val *SignupIds) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupIds) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupIds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupIds(val *SignupIds) *NullableSignupIds {
	return &NullableSignupIds{value: val, isSet: true}
}

func (v NullableSignupIds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupIds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


