/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package signups

import (
	"encoding/json"
)

// SignupInput Signup input values
type SignupInput struct {
	// Bank Name
	BankName string `json:"bank_name"`
	// Bank Short Code
	BankShortCode string `json:"bank_short_code"`
	// Partner Name
	PartnerName string `json:"partner_name"`
	// Bank's party's user_id
	UserId string `json:"user_id"`
}

// NewSignupInput instantiates a new SignupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupInput(bankName string, bankShortCode string, partnerName string, userId string) *SignupInput {
	this := SignupInput{}
	this.BankName = bankName
	this.BankShortCode = bankShortCode
	this.PartnerName = partnerName
	this.UserId = userId
	return &this
}

// NewSignupInputWithDefaults instantiates a new SignupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupInputWithDefaults() *SignupInput {
	this := SignupInput{}
	return &this
}

// GetBankName returns the BankName field value
func (o *SignupInput) GetBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value
// and a boolean to check if the value has been set.
func (o *SignupInput) GetBankNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BankName, true
}

// SetBankName sets field value
func (o *SignupInput) SetBankName(v string) {
	o.BankName = v
}

// GetBankShortCode returns the BankShortCode field value
func (o *SignupInput) GetBankShortCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankShortCode
}

// GetBankShortCodeOk returns a tuple with the BankShortCode field value
// and a boolean to check if the value has been set.
func (o *SignupInput) GetBankShortCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BankShortCode, true
}

// SetBankShortCode sets field value
func (o *SignupInput) SetBankShortCode(v string) {
	o.BankShortCode = v
}

// GetPartnerName returns the PartnerName field value
func (o *SignupInput) GetPartnerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartnerName
}

// GetPartnerNameOk returns a tuple with the PartnerName field value
// and a boolean to check if the value has been set.
func (o *SignupInput) GetPartnerNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PartnerName, true
}

// SetPartnerName sets field value
func (o *SignupInput) SetPartnerName(v string) {
	o.PartnerName = v
}

// GetUserId returns the UserId field value
func (o *SignupInput) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *SignupInput) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *SignupInput) SetUserId(v string) {
	o.UserId = v
}

func (o SignupInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bank_name"] = o.BankName
	}
	if true {
		toSerialize["bank_short_code"] = o.BankShortCode
	}
	if true {
		toSerialize["partner_name"] = o.PartnerName
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableSignupInput struct {
	value *SignupInput
	isSet bool
}

func (v NullableSignupInput) Get() *SignupInput {
	return v.value
}

func (v *NullableSignupInput) Set(val *SignupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupInput(val *SignupInput) *NullableSignupInput {
	return &NullableSignupInput{value: val, isSet: true}
}

func (v NullableSignupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


