/*
 * Synctera API
 *
 * <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p> 
 *
 * API version: 0.5.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounts

import (
	"encoding/json"
)

// ShadowModeAccount struct for ShadowModeAccount
type ShadowModeAccount struct {
	// Account ID
	Id *string `json:"id,omitempty"`
	// Account number
	AccountNumber string `json:"account_number"`
	// Account currency or account settlement currency. ISO 4217 alphabetic currency code. Default USD
	Currency *string `json:"currency,omitempty"`
	Status Status `json:"status"`
	// Account is investment (variable balance) account or a multi-balance account pool. Default false
	IsAccountPool *bool `json:"is_account_pool,omitempty"`
	// List of the relationship for this account to the parties
	Relationships *[]Relationship `json:"relationships,omitempty"`
	// A list of aliases for account. Account alias is the account number of different balance types to link to the same account ID
	Aliases *[]Alias `json:"aliases,omitempty"`
	// A list of balances for account based on different type
	Balances *[]Balance `json:"balances,omitempty"`
	// The most recent 10 transactions of the account
	RecentTransactions *[]Transaction `json:"recent_transactions,omitempty"`
}

// NewShadowModeAccount instantiates a new ShadowModeAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShadowModeAccount(accountNumber string, status Status) *ShadowModeAccount {
	this := ShadowModeAccount{}
	this.AccountNumber = accountNumber
	this.Status = status
	return &this
}

// NewShadowModeAccountWithDefaults instantiates a new ShadowModeAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShadowModeAccountWithDefaults() *ShadowModeAccount {
	this := ShadowModeAccount{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ShadowModeAccount) SetId(v string) {
	o.Id = &v
}

// GetAccountNumber returns the AccountNumber field value
func (o *ShadowModeAccount) GetAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetAccountNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccountNumber, true
}

// SetAccountNumber sets field value
func (o *ShadowModeAccount) SetAccountNumber(v string) {
	o.AccountNumber = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ShadowModeAccount) SetCurrency(v string) {
	o.Currency = &v
}

// GetStatus returns the Status field value
func (o *ShadowModeAccount) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetStatusOk() (*Status, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ShadowModeAccount) SetStatus(v Status) {
	o.Status = v
}

// GetIsAccountPool returns the IsAccountPool field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetIsAccountPool() bool {
	if o == nil || o.IsAccountPool == nil {
		var ret bool
		return ret
	}
	return *o.IsAccountPool
}

// GetIsAccountPoolOk returns a tuple with the IsAccountPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetIsAccountPoolOk() (*bool, bool) {
	if o == nil || o.IsAccountPool == nil {
		return nil, false
	}
	return o.IsAccountPool, true
}

// HasIsAccountPool returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasIsAccountPool() bool {
	if o != nil && o.IsAccountPool != nil {
		return true
	}

	return false
}

// SetIsAccountPool gets a reference to the given bool and assigns it to the IsAccountPool field.
func (o *ShadowModeAccount) SetIsAccountPool(v bool) {
	o.IsAccountPool = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetRelationships() []Relationship {
	if o == nil || o.Relationships == nil {
		var ret []Relationship
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetRelationshipsOk() (*[]Relationship, bool) {
	if o == nil || o.Relationships == nil {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasRelationships() bool {
	if o != nil && o.Relationships != nil {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given []Relationship and assigns it to the Relationships field.
func (o *ShadowModeAccount) SetRelationships(v []Relationship) {
	o.Relationships = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetAliases() []Alias {
	if o == nil || o.Aliases == nil {
		var ret []Alias
		return ret
	}
	return *o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetAliasesOk() (*[]Alias, bool) {
	if o == nil || o.Aliases == nil {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasAliases() bool {
	if o != nil && o.Aliases != nil {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []Alias and assigns it to the Aliases field.
func (o *ShadowModeAccount) SetAliases(v []Alias) {
	o.Aliases = &v
}

// GetBalances returns the Balances field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetBalances() []Balance {
	if o == nil || o.Balances == nil {
		var ret []Balance
		return ret
	}
	return *o.Balances
}

// GetBalancesOk returns a tuple with the Balances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetBalancesOk() (*[]Balance, bool) {
	if o == nil || o.Balances == nil {
		return nil, false
	}
	return o.Balances, true
}

// HasBalances returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasBalances() bool {
	if o != nil && o.Balances != nil {
		return true
	}

	return false
}

// SetBalances gets a reference to the given []Balance and assigns it to the Balances field.
func (o *ShadowModeAccount) SetBalances(v []Balance) {
	o.Balances = &v
}

// GetRecentTransactions returns the RecentTransactions field value if set, zero value otherwise.
func (o *ShadowModeAccount) GetRecentTransactions() []Transaction {
	if o == nil || o.RecentTransactions == nil {
		var ret []Transaction
		return ret
	}
	return *o.RecentTransactions
}

// GetRecentTransactionsOk returns a tuple with the RecentTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShadowModeAccount) GetRecentTransactionsOk() (*[]Transaction, bool) {
	if o == nil || o.RecentTransactions == nil {
		return nil, false
	}
	return o.RecentTransactions, true
}

// HasRecentTransactions returns a boolean if a field has been set.
func (o *ShadowModeAccount) HasRecentTransactions() bool {
	if o != nil && o.RecentTransactions != nil {
		return true
	}

	return false
}

// SetRecentTransactions gets a reference to the given []Transaction and assigns it to the RecentTransactions field.
func (o *ShadowModeAccount) SetRecentTransactions(v []Transaction) {
	o.RecentTransactions = &v
}

func (o ShadowModeAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["account_number"] = o.AccountNumber
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.IsAccountPool != nil {
		toSerialize["is_account_pool"] = o.IsAccountPool
	}
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	if o.Aliases != nil {
		toSerialize["aliases"] = o.Aliases
	}
	if o.Balances != nil {
		toSerialize["balances"] = o.Balances
	}
	if o.RecentTransactions != nil {
		toSerialize["recent_transactions"] = o.RecentTransactions
	}
	return json.Marshal(toSerialize)
}

type NullableShadowModeAccount struct {
	value *ShadowModeAccount
	isSet bool
}

func (v NullableShadowModeAccount) Get() *ShadowModeAccount {
	return v.value
}

func (v *NullableShadowModeAccount) Set(val *ShadowModeAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableShadowModeAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableShadowModeAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShadowModeAccount(val *ShadowModeAccount) *NullableShadowModeAccount {
	return &NullableShadowModeAccount{value: val, isSet: true}
}

func (v NullableShadowModeAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShadowModeAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


